apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany    
  nfs:
    server: nfs-server.default.svc.cluster.local ## This will be changed based on the name space
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkinsagentpvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
